spring.application.name=event_booking_service
server.port=8080

spring.jackson.time-zone=Asia/Kuala_Lumpur

spring.mongodb.username=${MONGO_USERNAME}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.host=${MONGO_HOST:localhost}
spring.mongodb.port=${MONGO_PORT:27017}
spring.mongodb.database=${MONGO_DATABASE:trainingdb}
spring.mongodb.authentication-database=${MONGO_AUTH_DATABASE:admin}

spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/uploads/**
# Allow larger file uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000

# optional for debugging
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO

logging.level.com.hba.event_booking_service=INFO
