spring.application.name=event_booking_service
server.port=8080

spring.jackson.time-zone=Asia/Kuala_Lumpur

spring.mongodb.username=user
spring.mongodb.password=password
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=trainingdb
spring.mongodb.authentication-database=admin

spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/uploads/**
# Allow larger file uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.secret=XhXH96vnxEAD1i53Jk+1w9/5RwMqjYXEZlGJUmj7udU=
app.jwt.expiration-ms=3600000

# optional for debugging
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO

logging.level.com.hba.event_booking_system=INFO
